// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


public class Colorable : MonoBehaviour {

	public AnimationCurve blinkCurve = new AnimationCurve(new Keyframe(0f, 0f), new Keyframe(.25f, .7f), new Keyframe(.5f, 0f), new Keyframe(.75f, .7f), new Keyframe(1f, 0f));
	public float blinkSpeed = 1f;

	private SpriteRenderer[] sRens;

	void Start() {
		sRens = GetComponentsInChildren<SpriteRenderer>();
	}


	private void SetColor(Color color) {
		foreach(SpriteRenderer sRen in sRens) {
			sRen.color = color;
		}
	}



	private bool redColor = false;
	private bool greenColor = false;
	private float t;
	void Update() {
		t += Time.deltaTime * blinkSpeed;
		if (t < 1f) {
			float curveValue = blinkCurve.Evaluate(t);
			Color newColor = Color.black;
			if (redColor) {
				newColor = new Color(1f, 1f - curveValue, 1f - curveValue);//white<->red transitions
			}
			if (greenColor) {
				newColor = new Color(1f - curveValue, 1f, 1f - curveValue);//white<->green transitions
			}
			SetColor( newColor );
		} else {
			enabled = false;
			t = 0;
			SetColor( Color.white );
		}
	}

	#region SendMessage handlers
	void OnTargeted() {
		t = 0;
		redColor = true;
		greenColor = false;
		enabled = true;
	}

	void OnSelected() {
		t = 0;
		redColor = false;
		greenColor = true;
		enabled = true;
	}
	#endregion
}

