// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Minion : MonoBehaviour {

	private CharController charController;
	private Fighter fighter;
	private Alive alive;

	void Start() {
		charController = GetComponent<CharController>();
		fighter = GetComponent<Fighter>();
		alive = GetComponent<Alive>();
	}

	public void Fight() {
		FightClosestTarget();
	}

	public bool IsDead() {
		return alive.IsDead;
	}

	private void FightClosestTarget() {
		TargetableByAI closestTarget = AI_Controller.Instance.GetClosestTarget(transform.position);
		if (closestTarget != null) {
			charController.Command_Attack( closestTarget.GetComponent<Alive>() );
		}
	}

	#region SendMessage handlers
	void OnTargetDead(Alive target) {
		FightClosestTarget();
	}

	void OnGotHit(Fighter attacker) {
		Alive attackersAlive = attacker.GetComponent<Alive>();
		if (!fighter.IsFighting && !attackersAlive.IsDead && !alive.IsDead) {
			charController.Command_Attack( attackersAlive );
		}
	}
	#endregion
}

